# Generated by Django 5.2.10 on 2026-02-05 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='institution_type',
            field=models.CharField(choices=[('primario', 'Ensino Primário'), ('complexo', 'Complexo Escolar (I e II Ciclos)'), ('medio', 'Ensino Médio Técnico'), ('colegio', 'Colégio / Liceu'), ('formacao', 'Centro de Formação')], default='complexo', max_length=20),
        ),
        migrations.CreateModel(
            name='SubAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('is_verified', models.BooleanField(default=False)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='client',
            name='sub_agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_clients', to='customers.subagent'),
        ),
    ]
