# Generated by Django 5.2.10 on 2026-01-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=25, unique=True)),
                ('account_holder', models.CharField(help_text='Nome do Titular', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebtAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installments_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='agreements/%Y/')),
                ('hash_control', models.CharField(blank=True, max_length=255)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Mensalidade, Documento', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('daily_interest_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('grace_period_days', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('FT', 'Fatura Crédito'), ('FR', 'Fatura Recibo'), ('FP', 'Fatura Proforma'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('AF', 'Autofacturação'), ('AC', 'Aviso de Cobrança'), ('RC', 'Recibo'), ('NL', 'Nota de Liquidação')], default='FT', max_length=2)),
                ('number', models.CharField(editable=False, max_length=50, unique=True)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('hash_control', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID or Receipt details', max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash_control', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payments/proofs/%Y/%m/', verbose_name='Comprovativo de Pagamento')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='payments/receipts/%Y/%m/', verbose_name='Recibo Oficial (PDF)')),
                ('validation_status', models.CharField(choices=[('pending', 'Aguardando Validação'), ('validated', 'Validado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Motivo caso o comprovativo seja inválido', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_entity_code', models.CharField(max_length=10, verbose_name='Entidade Multicaixa')),
                ('mc_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('card_api_public_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('method_type', models.CharField(choices=[('CH', 'Dinheiro / Cash'), ('TR', 'Transferência Bancária'), ('MC', 'Referência Multicaixa'), ('DP', 'Depósito Bancário')], default='CH', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_bank_account', models.BooleanField(default=False)),
                ('requires_file_upload', models.BooleanField(default=True)),
                ('auto_validate', models.BooleanField(default=False, help_text='Validar sem intervenção humana (ex: Referências)')),
            ],
        ),
    ]
