# Generated by Django 5.2.10 on 2026-03-06 15:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=21, unique=True)),
                ('account_holder', models.CharField(help_text='Nome do Titular', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DebtAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_debt_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('installments_count', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_pdf', models.FileField(blank=True, null=True, upload_to='agreements/%Y/')),
                ('hash_control', models.CharField(blank=True, max_length=255)),
                ('is_activated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Mensalidade, Documento', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurring', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FinanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('daily_interest_rate', models.DecimalField(decimal_places=2, default=0.1, max_digits=5)),
                ('grace_period_days', models.PositiveIntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('AF', 'Autofacturação'), ('AC', 'Aviso de Cobrança'), ('RC', 'Recibo'), ('NL', 'Nota de Liquidação'), ('VD', 'Venda a Dinheiro')], default='FT', max_length=2)),
                ('number', models.CharField(editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('overdue', 'Vencido')], default='pending', max_length=20)),
                ('hash_control', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('is_notified', models.BooleanField(default=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('discount_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor bruto ou % digitado', max_digits=15)),
                ('discount_is_pct', models.BooleanField(default=True, verbose_name='Desconto em %?')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor real abatido')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('waive_penalty', models.BooleanField(default=False)),
                ('waive_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(blank=True, help_text='Transaction ID or Receipt details', max_length=100)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hash_control', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payments/proofs/%Y/%m/', verbose_name='Comprovativo de Pagamento')),
                ('receipt_pdf', models.FileField(blank=True, null=True, upload_to='payments/receipts/%Y/%m/', verbose_name='Recibo Oficial (PDF)')),
                ('validation_status', models.CharField(choices=[('pending', 'Aguardando Validação'), ('validated', 'Validado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, help_text='Motivo caso o comprovativo seja inválido', null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mc_entity_code', models.CharField(max_length=10, verbose_name='Entidade Multicaixa')),
                ('mc_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('card_api_public_key', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('method_type', models.CharField(choices=[('CH', 'Dinheiro / Cash'), ('TR', 'Transferência Bancária'), ('MC', 'Referência Multicaixa'), ('DP', 'Depósito Bancário')], default='CH', max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_bank_account', models.BooleanField(default=False)),
                ('requires_file_upload', models.BooleanField(default=True)),
                ('auto_validate', models.BooleanField(default=False, help_text='Validar sem intervenção humana (ex: Referências)')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('bi_number', models.CharField(max_length=20, unique=True, verbose_name='Número do BI')),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=20)),
                ('category', models.CharField(help_text='Ex: Eletricista, Manutenção', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(help_text='Ex: Compra de material de limpeza', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('transaction_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída')], max_length=3)),
                ('category', models.CharField(help_text='Ex: Propinas, Salários, Manutenção', max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('outflow', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_entry', to='finance.cashoutflow')),
            ],
            options={
                'verbose_name': 'Fluxo de Caixa',
                'verbose_name_plural': 'Fluxos de Caixa',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Fundo de Maneio')),
                ('closing_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Saldo Final Declarado')),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('reported_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('difference', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('justification', models.TextField(blank=True, help_text='Justificativa em caso de divergência', null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de Caixa',
                'verbose_name_plural': 'Sessões de Caixa',
            },
        ),
        migrations.AddField(
            model_name='cashoutflow',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outflows', to='finance.cashsession'),
        ),
        migrations.CreateModel(
            name='CashInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(default='Reforço de Trocos', max_length=255)),
                ('authorized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflows', to='finance.cashsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
