# Generated by Django 5.2.10 on 2026-03-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceProvider',
        ),
        migrations.AlterField(
            model_name='feetype',
            name='name',
            field=models.CharField(help_text='Ex: Mensalidade, Matrícula, Reconfirmação', max_length=100),
        ),
        migrations.AlterField(
            model_name='feetype',
            name='recurring',
            field=models.BooleanField(default=False, help_text='Marcar True para Propinas mensais'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='doc_type',
            field=models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('RC', 'Recibo'), ('NL', 'Nota de Liquidação')], default='FT', max_length=2),
        ),
    ]
