# Generated by Django 5.2.10 on 2026-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_invoiceitem_competence_month_feepricehistory_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feepricehistory',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Histórico de Preço'},
        ),
        migrations.RenameField(
            model_name='feepricehistory',
            old_name='changed_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='feepricehistory',
            name='changed_by',
        ),
        migrations.AddField(
            model_name='feepricehistory',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feepricehistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
