# Generated by Django 5.2.10 on 2026-03-26 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_bankaccount_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='finance.cashsession', verbose_name='Sessão de Caixa'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='doc_type',
            field=models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('RC', 'Recibo'), ('NL', 'Nota de Liquidação')], default='FR', max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_type',
            field=models.CharField(choices=[('CH', 'Dinheiro / Cash'), ('TR', 'Transferência Bancária'), ('MC', 'Referência Multicaixa'), ('DP', 'Depósito Bancário')], default='DP', max_length=2),
        ),
    ]
