# Generated by Django 5.2.10 on 2026-03-26 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_payment_cash_session_alter_invoice_doc_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='doc_type',
            field=models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('NC', 'Nota de Crédito'), ('RC', 'Recibo')], default='FT', max_length=2),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('number', models.CharField(editable=False, max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hash_control', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('atcud', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='official_receipt', to='finance.payment')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
            },
        ),
    ]
