# Generated by Django 5.2.10 on 2026-03-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_invoice_doc_type_receipt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={},
        ),
        migrations.AlterField(
            model_name='receipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='atcud',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
