# Generated by Django 5.2.10 on 2026-03-26 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_receipt_options_alter_receipt_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_printed',
            field=models.BooleanField(default=False, verbose_name='Impressa'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='printed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='printed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='printed_invoices', to=settings.AUTH_USER_MODEL),
        ),
    ]
