# Generated by Django 5.2.10 on 2026-03-29 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_invoice_is_printed_invoice_printed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='numero_sequencial',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='serie_codigo',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
    ]
