# Generated by Django 5.2.10 on 2026-03-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_receipt_numero_sequencial_receipt_serie_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='atcud',
        ),
    ]
