# Generated by Django 5.2.10 on 2026-03-06 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('registration_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Official Full Name', max_length=255)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('is_suspended', models.BooleanField(default=False, help_text='Bloqueia acesso por falta de pagamento')),
                ('is_blocked_for_fraud', models.BooleanField(default=False, verbose_name='Bloqueio de Segurança (Fraude)')),
                ('fraud_lock_details', models.TextField(blank=True, null=True, verbose_name='Detalhes da Infração Técnica')),
                ('current_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_students', to='academic.class')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_students', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('request_type', models.CharField(choices=[('NEW', 'Nova Matrícula'), ('RECONFIRMATION', 'Reconfirmação')], default='NEW', max_length=20, verbose_name='Tipo de Solicitação')),
                ('guardian_name', models.CharField(blank=True, max_length=255)),
                ('guardian_phone', models.CharField(blank=True, max_length=50)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('doc_bi', models.FileField(blank=True, null=True, upload_to='candidates/bi/')),
                ('doc_health', models.FileField(blank=True, null=True, upload_to='candidates/health/')),
                ('doc_payment_proof', models.FileField(blank=True, null=True, upload_to='candidates/payments/%Y/', verbose_name='Comprovativo de Pagamento')),
                ('doc_certificate', models.FileField(blank=True, null=True, upload_to='candidates/certificates/%Y/')),
                ('photo_passport', models.ImageField(blank=True, null=True, upload_to='candidates/photos/%Y/')),
                ('has_special_needs', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente Análise'), ('paid', 'Pago / Em Processamento'), ('approved', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=20)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.course')),
                ('grade_level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.gradelevel')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoice')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('pending_placement', 'Aguardando Colocação'), ('transferred', 'Transferido'), ('dropout', 'Desistente'), ('graduated', 'Graduado'), ('failed', 'Reprovado')], default='active', max_length=20)),
                ('date_enrolled', models.DateField(auto_now_add=True)),
                ('order_number', models.PositiveIntegerField(default=1, help_text='Número de ordem na pauta')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.academicyear')),
                ('class_room', models.ForeignKey(blank=True, help_text='Turma', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments_records', to='academic.class')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('father', 'Father'), ('mother', 'Mother'), ('uncle', 'Uncle'), ('aunt', 'Aunt'), ('grandparent', 'Grandparent'), ('other', 'Other')], max_length=20)),
                ('is_financial_responsible', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='students.guardian')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'guardian')},
            },
        ),
    ]
