# Generated by Django 5.2.10 on 2026-03-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='merit_points',
            field=models.IntegerField(default=0, verbose_name='Pontos de Mérito Académico'),
        ),
    ]
