# Generated by Django 5.2.10 on 2026-01-25 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_lessonplan_studentauditlog'),
        ('finance', '0002_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='gender',
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='enrollment_requests', to='students.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_room',
            field=models.ForeignKey(blank=True, help_text='Turma', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments_records', to='academic.class'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Ativo'), ('pending_placement', 'Aguardando Colocação'), ('transferred', 'Transferido'), ('dropout', 'Desistente'), ('graduated', 'Graduado'), ('failed', 'Reprovado')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.course'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='doc_bi',
            field=models.FileField(blank=True, null=True, upload_to='candidates/bi/'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='doc_health',
            field=models.FileField(blank=True, null=True, upload_to='candidates/health/'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='grade_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.gradelevel'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='guardian_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='invoice',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoice'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente Pagamento'), ('paid', 'Pago / Em Análise'), ('approved', 'Matriculado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
    ]
