# Generated by Django 5.2.10 on 2026-03-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_merit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bi_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Número do BI'),
        ),
    ]
