# Generated by Django 5.2.10 on 2026-01-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_enrollmentrequest_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='doc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='candidates/certificates/%Y/', verbose_name='Certificado/Declaração'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='has_special_needs',
            field=models.BooleanField(default=False, verbose_name='Necessidades Especiais?'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações/Saúde'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='photo_passport',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/photos/%Y/', verbose_name='Foto Tipo Passe'),
        ),
    ]
