# Generated by Django 5.2.10 on 2026-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_enrollmentrequest_doc_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='doc_payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='candidates/payments/%Y/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='request_type',
            field=models.CharField(choices=[('NEW', 'Nova Matrícula'), ('RECONFIRMATION', 'Reconfirmação')], default='NEW', max_length=20, verbose_name='Tipo de Solicitação'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente Análise'), ('paid', 'Pago / Em Processamento'), ('approved', 'Confirmado'), ('rejected', 'Rejeitado')], default='pending', max_length=20),
        ),
    ]
