# Generated by Django 5.2.10 on 2026-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_bi_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentguardian',
            name='relationship',
            field=models.CharField(choices=[('father', 'Pai'), ('mother', 'Mãe'), ('uncle', 'Tio'), ('aunt', 'Tia'), ('grandparent', 'Avó/Avô'), ('other', 'Outros')], max_length=20),
        ),
    ]
