# Generated by Django 5.2.10 on 2026-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_enrollmentrequest_doc_payment_proof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='doc_certificate',
            field=models.FileField(blank=True, null=True, upload_to='candidates/certificates/%Y/'),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='has_special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='photo_passport',
            field=models.ImageField(blank=True, null=True, upload_to='candidates/photos/%Y/'),
        ),
    ]
