# Generated by Django 5.2.10 on 2026-01-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_enrollmentrequest_doc_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='registration_number',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
