# Generated by Django 5.2.10 on 2026-03-21 02:34

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='photo_passport',
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='photo_passport_file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo_passport_file'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Endereço'),
        ),
    ]
