# Generated by Django 5.2.10 on 2026-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_alter_student_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fraud_lock_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da Infração Técnica'),
        ),
        migrations.AddField(
            model_name='student',
            name='is_blocked_for_fraud',
            field=models.BooleanField(default=False, verbose_name='Bloqueio de Segurança (Fraude)'),
        ),
    ]
