# Generated by Django 5.2.10 on 2026-03-26 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_gradelevel_total_monthly_fee'),
        ('students', '0006_remove_enrollmentrequest_photo_passport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='grade_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.gradelevel'),
        ),
    ]
