# Generated by Django 5.2.10 on 2026-03-27 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_gradelevel_total_monthly_fee'),
        ('students', '0007_enrollment_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='grade_level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academic.gradelevel'),
            preserve_default=False,
        ),
    ]
