# Generated by Django 5.2.10 on 2026-02-05 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_initial'),
        ('finance', '0003_serviceprovider_invoice_discount_amount_and_more'),
        ('fiscal', '0002_documentocanceladoaudit_logintegracaoagt_and_more'),
        ('students', '0007_student_fraud_lock_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(default='9999999999', max_length=20, verbose_name='NIF')),
                ('client_type', models.CharField(choices=[('STAFF', 'Funcionário/Professor'), ('VISITOR', 'Visitante/Outro')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CafeteriaSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(choices=[('WALLET', 'Carteira'), ('CASH', 'Cash'), ('MULTICAIXA', 'TPA')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_final', models.DecimalField(decimal_places=2, max_digits=15)),
                ('authorized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fiscal_doc', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscal.documentofiscal')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='finance.cashsession')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.student')),
                ('tax_rate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt')),
                ('external_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafeteria.externalclient')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
