# Generated by Django 5.2.10 on 2026-03-06 15:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('FINANCE', 'Finanças'), ('ACADEMIC', 'Académico'), ('SETUP', 'Configuração Inicial')], max_length=50)),
                ('content', models.TextField()),
                ('icon', models.CharField(default='fa-question-circle', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('applied_area', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='recruitment/cvs/%Y/', verbose_name='Curriculum Vitae')),
                ('bi_file', models.FileField(blank=True, null=True, upload_to='recruitment/docs/%Y/', verbose_name='Bilhete de Identidade')),
                ('academic_cert', models.FileField(blank=True, null=True, upload_to='recruitment/docs/%Y/', verbose_name='Certificado Literário')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('INTERVIEW', 'Entrevista Agendada'), ('HIRED', 'Admitido / Contratado'), ('REJECTED', 'Não Selecionado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor Geral'), ('PEDAGOGIC', 'Diretor Pedagógico'), ('DIRECT_ADMIN', 'Dr. Administrativo'), ('DIRECT_FINANC', 'Dr. Financeiro'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('VIGILANT', 'Vigilante'), ('ACCOUNTANT', 'Contabilista'), ('RH', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='CUSTOM', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted.')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('school_name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(max_length=20, verbose_name='NIF/Contribuinte')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/logos/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/favicons/')),
                ('weight_mac', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso da Média de Avaliação Contínua', max_digits=3)),
                ('weight_npp', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso da Nota de Prova Parcial', max_digits=3)),
                ('weight_npt', models.DecimalField(decimal_places=2, default=1.0, help_text='Peso da Nota de Prova Trimestral/Final', max_digits=3)),
                ('current_quarter', models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')], default=1, verbose_name='Trimestre Ativo')),
                ('primary_color', models.CharField(default='#4f46e5', help_text='Cor principal', max_length=7)),
                ('secondary_color', models.CharField(default='#1e293b', help_text='Cor secundária', max_length=7)),
                ('site_header_bg', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Fundo do Cabeçalho')),
                ('site_header_text', models.CharField(default='#1e293b', max_length=7, verbose_name='Texto do Cabeçalho')),
                ('site_footer_bg', models.CharField(default='#FFFFFF', max_length=7, verbose_name='Fundo do Rodapé')),
                ('site_footer_text', models.CharField(default='#64748b', max_length=7, verbose_name='Texto do Rodapé')),
                ('site_info_cards', models.JSONField(blank=True, default=list, verbose_name='Cards Informativos')),
                ('official_email', models.EmailField(max_length=254)),
                ('phone_contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('is_recruitment_open', models.BooleanField(default=False, verbose_name='Recrutamento Aberto')),
                ('available_job_areas', models.TextField(blank=True, default='', help_text='Separe as áreas disponíveis por vírgula.')),
                ('allow_secretary_edit_student', models.BooleanField(default=False, verbose_name='Permitir Secretaria Editar Alunos')),
                ('allow_teacher_view_full_file', models.BooleanField(default=False, verbose_name='Permitir Professor ver Ficha Completa')),
                ('allow_secretary_view_finance', models.BooleanField(default=False, verbose_name='Permitir Secretaria ver Financeiro')),
                ('website_link', models.URLField(blank=True, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('news_ticker', models.CharField(blank=True, max_length=255, verbose_name='Novidades (Ticker)')),
                ('custom_html_content', models.TextField(blank=True, verbose_name='Conteúdo Estático/HTML')),
                ('hero_mode', models.CharField(choices=[('CAROUSEL', 'Modo Carrossel (3 Slides)'), ('SINGLE', 'Imagem Única (Hero)'), ('MINIMAL', 'Sem Imagem (Minimalista)')], default='SINGLE', max_length=10)),
                ('hero_title', models.CharField(default='Educação de Excelência', max_length=100)),
                ('hero_subtitle', models.TextField(default='Preparando líderes para o futuro.')),
                ('hero_image_1', models.ImageField(blank=True, null=True, upload_to='branding/hero/')),
                ('hero_image_2', models.ImageField(blank=True, null=True, upload_to='branding/hero/')),
                ('hero_image_3', models.ImageField(blank=True, null=True, upload_to='branding/hero/')),
                ('is_enrollment_open', models.BooleanField(default=True, help_text='Chave geral. Se desligado, ninguém se matricula.', verbose_name='Matrículas Abertas (Manual)')),
                ('enrollment_start_date', models.DateField(blank=True, null=True, verbose_name='Início das Matrículas')),
                ('enrollment_end_date', models.DateField(blank=True, null=True, verbose_name='Fim das Matrículas')),
                ('is_reconfirmation_open', models.BooleanField(default=False, help_text='Chave geral para alunos antigos.', verbose_name='Reconfirmações Abertas (Manual)')),
                ('reconfirmation_start_date', models.DateField(blank=True, null=True, verbose_name='Início das Reconfirmações')),
                ('reconfirmation_end_date', models.DateField(blank=True, null=True, verbose_name='Fim das Reconfirmações')),
                ('allow_secretary_export', models.BooleanField(default=False)),
                ('allow_secretary_import', models.BooleanField(default=False)),
                ('allow_teacher_export', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(choices=[('COMPLIMENT', 'Elogio'), ('INCIDENT', 'Ocorrência Disciplinar'), ('ACADEMIC', 'Alerta Académico'), ('GENERAL', 'Informativo Geral')], default='GENERAL', max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('in_progress', 'Em Atendimento'), ('closed', 'Resolvido')], default='open', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('current_role', models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor Geral'), ('PEDAGOGIC', 'Diretor Pedagógico'), ('DIRECT_ADMIN', 'Dr. Administrativo'), ('DIRECT_FINANC', 'Dr. Financeiro'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('VIGILANT', 'Vigilante'), ('ACCOUNTANT', 'Contabilista'), ('RH', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='ADMIN', max_length=20)),
                ('pode_acessar_academic_page', models.BooleanField(default=False)),
                ('pode_ver_pautas_boletins', models.BooleanField(default=False)),
                ('pode_ver_documentos_academics', models.BooleanField(default=False)),
                ('pode_baixar_pautas', models.BooleanField(default=False)),
                ('pode_baixar_boletins', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
