# Generated by Django 5.2.10 on 2026-01-23 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalSchoolConfiguration',
        ),
    ]
