# Generated by Django 5.2.10 on 2026-01-25 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_globalschoolconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='allow_secretary_export',
            field=models.BooleanField(default=False, verbose_name='Permitir Exportação (Secretaria)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='allow_secretary_import',
            field=models.BooleanField(default=False, verbose_name='Permitir Importação (Secretaria)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='allow_teacher_export',
            field=models.BooleanField(default=False, verbose_name='Permitir Exportação (Professor)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='is_enrollment_open',
            field=models.BooleanField(default=True, help_text="Se falso, esconde o botão de 'Nova Matrícula' para a Secretaria.", verbose_name='Matrículas Abertas'),
        ),
    ]
