# Generated by Django 5.2.10 on 2026-03-21 02:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_image_1',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image_1'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_image_2',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image_2'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_image_3',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='hero_image_3'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='logo'),
        ),
    ]
