# Generated by Django 5.2.10 on 2026-03-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_schoolconfiguration_favicon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='tax_id',
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='nif',
            field=models.CharField(default='timezone.now', max_length=20, verbose_name='NIF/Contribuinte'),
            preserve_default=False,
        ),
    ]
