# Generated by Django 5.2.10 on 2026-01-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_schoolconfiguration_allow_secretary_export_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook da Escola'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram da Escola'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn da Escola'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='website_link',
            field=models.URLField(blank=True, null=True, verbose_name='Website Oficial'),
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('ACCOUNTANT', 'Contabilista'), ('HR', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('ACCOUNTANT', 'Contabilista'), ('HR', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='ADMIN', max_length=20),
        ),
    ]
