# Generated by Django 5.2.10 on 2026-01-26 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_schoolconfiguration_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolmessage',
            name='hero_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/', verbose_name='Imagem 1 / Principal'),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='hero_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/', verbose_name='Imagem 2 (Carrossel)'),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/', verbose_name='Imagem 3 (Carrossel)'),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='hero_mode',
            field=models.CharField(choices=[('CAROUSEL', 'Modo Carrossel (3 Slides)'), ('SINGLE', 'Imagem Única (Hero)'), ('MINIMAL', 'Sem Imagem (Minimalista)')], default='SINGLE', max_length=10, verbose_name='Modo de Exibição'),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='hero_subtitle',
            field=models.TextField(default='Preparando líderes para o futuro.', verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='schoolmessage',
            name='hero_title',
            field=models.CharField(default='Educação de Excelência', max_length=100, verbose_name='Título Principal'),
        ),
    ]
