# Generated by Django 5.2.10 on 2026-01-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_schoolmessage_hero_image_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolmessage',
            name='hero_image_1',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='hero_image_2',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='hero_image_3',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='hero_mode',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='schoolmessage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='hero_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/', verbose_name='Imagem 1 / Principal'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='hero_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/', verbose_name='Imagem 2 (Carrossel)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/', verbose_name='Imagem 3 (Carrossel)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='hero_mode',
            field=models.CharField(choices=[('CAROUSEL', 'Modo Carrossel (3 Slides)'), ('SINGLE', 'Imagem Única (Hero)'), ('MINIMAL', 'Sem Imagem (Minimalista)')], default='SINGLE', max_length=10, verbose_name='Modo de Exibição'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='hero_subtitle',
            field=models.TextField(default='Preparando líderes para o futuro.', verbose_name='Subtítulo'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='hero_title',
            field=models.CharField(default='Educação de Excelência', max_length=100, verbose_name='Título Principal'),
        ),
    ]
