# Generated by Django 5.2.10 on 2026-01-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_schoolmessage_hero_image_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='custom_html_content',
            field=models.TextField(blank=True, help_text='Área para embed de vídeos, iframes de animações ou código HTML personalizado para a Home.', verbose_name='Conteúdo Estático/HTML'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='news_ticker',
            field=models.CharField(blank=True, help_text="Texto curto para a barra de novidades (ex: 'Inscrições abertas até dia 30!')", max_length=255, verbose_name='Novidades (Ticker)'),
        ),
    ]
