# Generated by Django 5.2.10 on 2026-01-25 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_schoolconfiguration_custom_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='site_footer_bg',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Fundo do Rodapé'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='site_footer_text',
            field=models.CharField(default='#64748b', max_length=7, verbose_name='Texto do Rodapé'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='site_header_bg',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Fundo do Cabeçalho'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='site_header_text',
            field=models.CharField(default='#1e293b', max_length=7, verbose_name='Texto do Cabeçalho'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='site_info_cards',
            field=models.JSONField(blank=True, default=list, help_text='Lista de destaques da página inicial.', verbose_name='Cards Informativos'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='custom_html_content',
            field=models.TextField(blank=True, help_text='Área para embed de vídeos, iframes de animações ou código HTML personalizado.', verbose_name='Conteúdo Estático/HTML'),
        ),
    ]
