# Generated by Django 5.2.10 on 2026-01-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_schoolconfiguration_site_footer_bg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='enrollment_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Matrículas'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='enrollment_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início das Matrículas'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='is_reconfirmation_open',
            field=models.BooleanField(default=False, help_text='Chave geral para alunos antigos garantirem vaga.', verbose_name='Reconfirmações Abertas (Manual)'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='reconfirmation_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim das Reconfirmações'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='reconfirmation_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Início das Reconfirmações'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='is_enrollment_open',
            field=models.BooleanField(default=True, help_text='Chave geral. Se desligado, ninguém se matricula, independente da data.', verbose_name='Matrículas Abertas (Manual)'),
        ),
    ]
