# Generated by Django 5.2.10 on 2026-01-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_schoolconfiguration_enrollment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='allow_secretary_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='allow_secretary_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='allow_teacher_export',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='custom_html_content',
            field=models.TextField(blank=True, verbose_name='Conteúdo Estático/HTML'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='branding/hero/'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_mode',
            field=models.CharField(choices=[('CAROUSEL', 'Modo Carrossel (3 Slides)'), ('SINGLE', 'Imagem Única (Hero)'), ('MINIMAL', 'Sem Imagem (Minimalista)')], default='SINGLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_subtitle',
            field=models.TextField(default='Preparando líderes para o futuro.'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='hero_title',
            field=models.CharField(default='Educação de Excelência', max_length=100),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='instagram_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='is_enrollment_open',
            field=models.BooleanField(default=True, help_text='Chave geral. Se desligado, ninguém se matricula.', verbose_name='Matrículas Abertas (Manual)'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='is_reconfirmation_open',
            field=models.BooleanField(default=False, help_text='Chave geral para alunos antigos.', verbose_name='Reconfirmações Abertas (Manual)'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='linkedin_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='news_ticker',
            field=models.CharField(blank=True, max_length=255, verbose_name='Novidades (Ticker)'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='primary_color',
            field=models.CharField(default='#4f46e5', help_text='Cor principal', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='secondary_color',
            field=models.CharField(default='#1e293b', help_text='Cor secundária', max_length=7),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='site_info_cards',
            field=models.JSONField(blank=True, default=list, verbose_name='Cards Informativos'),
        ),
        migrations.AlterField(
            model_name='schoolconfiguration',
            name='website_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
