# Generated by Django 5.2.10 on 2026-01-28 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_schoolconfiguration_allow_secretary_export_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('iban', models.CharField(max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('purpose', models.CharField(default='Geral', help_text='Finalidade da conta', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_accounts', to='core.schoolconfiguration')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
