# Generated by Django 5.2.10 on 2026-01-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_schoolbankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('applied_area', models.CharField(max_length=100)),
                ('cv_file', models.FileField(upload_to='recruitment/cvs/%Y/', verbose_name='Curriculum Vitae')),
                ('bi_file', models.FileField(blank=True, null=True, upload_to='recruitment/docs/%Y/', verbose_name='Bilhete de Identidade')),
                ('academic_cert', models.FileField(blank=True, null=True, upload_to='recruitment/docs/%Y/', verbose_name='Certificado Literário')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('INTERVIEW', 'Entrevista Agendada'), ('HIRED', 'Admitido / Contratado'), ('REJECTED', 'Não Selecionado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, verbose_name='Notas Internas')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='available_job_areas',
            field=models.TextField(blank=True, default='', help_text='Separe as áreas disponíveis por vírgula.'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='is_recruitment_open',
            field=models.BooleanField(default=False, verbose_name='Recrutamento Aberto'),
        ),
    ]
