# Generated by Django 5.2.10 on 2026-01-29 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_jobapplication_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('ACCOUNTANT', 'Contabilista'), ('RH', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('ACCOUNTANT', 'Contabilista'), ('RH', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='ADMIN', max_length=20),
        ),
    ]
