# Generated by Django 5.2.10 on 2026-01-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_role_code_alter_user_current_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='allow_secretary_edit_student',
            field=models.BooleanField(default=False, verbose_name='Permitir Secretaria Editar Alunos'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='allow_secretary_view_finance',
            field=models.BooleanField(default=False, verbose_name='Permitir Secretaria ver Financeiro'),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='allow_teacher_view_full_file',
            field=models.BooleanField(default=False, verbose_name='Permitir Professor ver Ficha Completa'),
        ),
    ]
