# Generated by Django 5.2.10 on 2026-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_schoolconfiguration_allow_secretary_edit_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='weight_mac',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso da Média de Avaliação Contínua', max_digits=3),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='weight_npp',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso da Nota de Prova Parcial', max_digits=3),
        ),
        migrations.AddField(
            model_name='schoolconfiguration',
            name='weight_npt',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Peso da Nota de Prova Trimestral/Final', max_digits=3),
        ),
        migrations.AddField(
            model_name='user',
            name='pode_acessar_academic_page',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pode_baixar_boletins',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pode_baixar_pautas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pode_ver_documentos_academics',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='pode_ver_pautas_boletins',
            field=models.BooleanField(default=False),
        ),
    ]
