# Generated by Django 5.2.10 on 2026-02-02 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_schoolconfiguration_weight_mac_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='current_quarter',
            field=models.IntegerField(choices=[(1, '1º Trimestre'), (2, '2º Trimestre'), (3, '3º Trimestre')], default=1, verbose_name='Trimestre Ativo'),
        ),
    ]
