# Generated by Django 5.2.10 on 2026-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_schoolconfiguration_current_quarter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='bank_name',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='iban_primary',
        ),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor Geral'), ('PEDAGOGIC', 'Diretor Pedagógico'), ('DIRECT_ADMIN', 'Dr. Administrativo'), ('DIRECT_FINANC', 'Dr. Financeiro'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('VIGILANT', 'Vigilante'), ('ACCOUNTANT', 'Contabilista'), ('RH', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='CUSTOM', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DIRECTOR', 'Diretor Geral'), ('PEDAGOGIC', 'Diretor Pedagógico'), ('DIRECT_ADMIN', 'Dr. Administrativo'), ('DIRECT_FINANC', 'Dr. Financeiro'), ('TEACHER', 'Professor'), ('STUDENT', 'Aluno'), ('GUARDIAN', 'Encarregado'), ('SECRETARY', 'Secretaria'), ('VIGILANT', 'Vigilante'), ('ACCOUNTANT', 'Contabilista'), ('RH', 'Recursos Humanos'), ('CUSTOM', 'Customizado')], default='ADMIN', max_length=20),
        ),
        migrations.DeleteModel(
            name='SchoolBankAccount',
        ),
    ]
