# Generated by Django 5.2.10 on 2026-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_schoolconfiguration_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolconfiguration',
            name='is_pedagogical_break',
            field=models.BooleanField(default=False),
        ),
    ]
