# Generated by Django 5.2.10 on 2026-02-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_schoolconfiguration_is_pedagogical_break'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='is_pedagogical_break',
        ),
    ]
