# Generated by Django 5.2.10 on 2026-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='is_in_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
