# Generated by Django 5.2.10 on 2026-02-06 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_bus_current_lat_bus_current_lng_bus_is_in_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busevent',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='busevent',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='busevent',
            name='event_type',
            field=models.CharField(choices=[('IN', 'Embarque'), ('OUT', 'Desembarque (Escola)'), ('HOME', 'Entregue em Casa')], max_length=5),
        ),
    ]
