# Generated by Django 5.2.10 on 2026-03-06 15:57

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('descricao', models.CharField(default='Chaves AGT 2026', max_length=100)),
                ('chave_privada_pem', models.TextField(help_text='Chave privada RSA para assinatura de faturas.')),
                ('chave_publica_pem', models.TextField(help_text='Chave pública para validação.')),
                ('ativa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cofre Digital da Escola',
            },
        ),
        migrations.CreateModel(
            name='FiscalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('saft_generation_day', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('auto_submit_agt', models.BooleanField(default=False)),
                ('email_notification', models.EmailField(blank=True, max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SAFTExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('periodo_tributacao', models.CharField(max_length=7)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='saft_xml/%Y/%m/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('log_erros', models.TextField(blank=True)),
                ('sent_to_email', models.TextField(blank=True, help_text='Emails dos contabilistas que receberam', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('dispatch_log', models.TextField(blank=True, help_text='Log técnico da transação SMTP')),
            ],
            options={
                'verbose_name': 'Exportação SAF-T',
                'verbose_name_plural': 'Exportações SAF-T',
            },
        ),
        migrations.CreateModel(
            name='SerieFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('tipo_documento', models.CharField(max_length=10)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='PENDING', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaxaIVAAGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('nome', models.CharField(max_length=100)),
                ('tax_type', models.CharField(choices=[('IVA', 'IVA'), ('IS', 'Isenção'), ('NS', 'Não Sujeição')], max_length=3)),
                ('tax_code', models.CharField(choices=[('NOR', 'Normal'), ('INT', 'Intercalar'), ('RED', 'Reduzida'), ('ISE', 'Isento'), ('NSU', 'Não Sujeito')], max_length=3)),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('exemption_reason', models.CharField(blank=True, max_length=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Taxa de IVA (AGT)',
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_documento', models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('AF', 'Autofacturação'), ('AC', 'Aviso de Cobrança'), ('RC', 'Recibo'), ('NL', 'Nota de Liquidação'), ('VD', 'Venda a Dinheiro')], default='FT', max_length=3)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('cancelled', 'Anulado')], default='draft', max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('numero', models.PositiveIntegerField()),
                ('numero_documento', models.CharField(editable=False, max_length=50, unique=True)),
                ('atcud', models.CharField(blank=True, max_length=70)),
                ('agt_request_id', models.CharField(blank=True, max_length=50)),
                ('agt_status', models.CharField(default='PENDING', max_length=20)),
                ('agt_log', models.TextField(blank=True)),
                ('entidade_nome', models.CharField(max_length=200)),
                ('entidade_nif', models.CharField(default='9999999999', max_length=20)),
                ('data_emissao', models.DateField()),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('hash_documento', models.CharField(blank=True, max_length=256)),
                ('hash_anterior', models.CharField(blank=True, max_length=256)),
                ('saft_hash', models.CharField(blank=True, max_length=256)),
                ('periodo_tributacao', models.CharField(max_length=7)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='students.student')),
                ('usuario_criacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_emissao', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCanceladoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField(verbose_name='Motivo Legal da Anulação')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP do Terminal')),
                ('user_agent', models.TextField(verbose_name='Dados do Navegador/Dispositivo')),
                ('valor_estornado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacao_audit', to='fiscal.documentofiscal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogIntegracaoAGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.URLField(help_text='URL da API da AGT acessada')),
                ('xml_sent', models.TextField(blank=True, verbose_name='XML Enviado')),
                ('response_received', models.TextField(blank=True, verbose_name='Resposta da AGT')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_agt', to='fiscal.documentofiscal')),
            ],
            options={
                'verbose_name': 'Log de Integração AGT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoFiscalLinha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total_linha', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_iva_linha', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_linha', models.PositiveIntegerField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linhas', to='fiscal.documentofiscal')),
                ('taxa_iva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt')),
            ],
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['atcud'], name='fiscal_docu_atcud_f78591_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['hash_documento'], name='fiscal_docu_hash_do_062bea_idx'),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['periodo_tributacao'], name='fiscal_docu_periodo_94cf31_idx'),
        ),
    ]
