# Generated by Django 5.2.10 on 2026-02-05 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
        ('students', '0007_student_fraud_lock_details_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCanceladoAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('justificativa', models.TextField(verbose_name='Motivo Legal da Anulação')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Endereço IP do Terminal')),
                ('user_agent', models.TextField(verbose_name='Dados do Navegador/Dispositivo')),
                ('valor_estornado', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LogIntegracaoAGT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.URLField(help_text='URL da API da AGT acessada')),
                ('xml_sent', models.TextField(blank=True, verbose_name='XML Enviado')),
                ('response_received', models.TextField(blank=True, verbose_name='Resposta da AGT')),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('sucesso', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Log de Integração AGT',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='saftexport',
            options={'verbose_name': 'Exportação SAF-T', 'verbose_name_plural': 'Exportações SAF-T'},
        ),
        migrations.AddField(
            model_name='saftexport',
            name='dispatch_log',
            field=models.TextField(blank=True, help_text='Log técnico da transação SMTP'),
        ),
        migrations.AddField(
            model_name='saftexport',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saftexport',
            name='sent_to_email',
            field=models.TextField(blank=True, help_text='Emails dos contabilistas que receberam', null=True),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos_fiscais', to='students.student'),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='entidade_nif',
            field=models.CharField(default='9999999999', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentofiscal',
            name='tipo_documento',
            field=models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('AF', 'Autofacturação'), ('AC', 'Aviso de Cobrança'), ('RC', 'Recibo'), ('NL', 'Nota de Liquidação'), ('VD', 'Venda a Dinheiro')], default='FT', max_length=3),
        ),
        migrations.AddIndex(
            model_name='documentofiscal',
            index=models.Index(fields=['periodo_tributacao'], name='fiscal_docu_periodo_94cf31_idx'),
        ),
        migrations.AddField(
            model_name='documentocanceladoaudit',
            name='documento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anulacao_audit', to='fiscal.documentofiscal'),
        ),
        migrations.AddField(
            model_name='documentocanceladoaudit',
            name='operador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='logintegracaoagt',
            name='documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs_agt', to='fiscal.documentofiscal'),
        ),
    ]
