# Generated by Django 5.2.10 on 2026-03-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='tipo_documento',
            field=models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('ND', 'Nota de Débito'), ('NC', 'Nota de Crédito'), ('RC', 'Recibo'), ('NL', 'Nota de Liquidação')], default='FT', max_length=3),
        ),
    ]
