# Generated by Django 5.2.10 on 2026-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0003_alter_documentofiscal_tipo_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentofiscal',
            name='tipo_documento',
            field=models.CharField(choices=[('FT', 'Fatura'), ('FR', 'Fatura-Recibo'), ('FP', 'Fatura Proforma'), ('NC', 'Nota de Crédito'), ('RC', 'Recibo')], default='FT', max_length=3),
        ),
    ]
