# Generated by Django 5.2.10 on 2026-03-29 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0004_alter_documentofiscal_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentofiscal',
            name='serie',
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='serie_codigo',
            field=models.CharField(default='PROVISORIO', editable=False, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentofiscal',
            name='serie_fiscal',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='fiscal.seriefiscal'),
            preserve_default=False,
        ),
    ]
