# Generated by Django 5.2.10 on 2026-03-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0005_remove_documentofiscal_serie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentofiscal',
            old_name='serie_fiscal',
            new_name='serie',
        ),
    ]
