# Generated by Django 5.2.10 on 2026-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0006_rename_serie_fiscal_documentofiscal_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='seriefiscal',
            name='codigo_validacao_agt',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
