# Generated by Django 5.2.10 on 2026-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fiscal', '0007_seriefiscal_codigo_validacao_agt'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentofiscal',
            name='documento_origem',
            field=models.CharField(blank=True, help_text='Referência ao documento que originou este (Ex: FT SERIE/1)', max_length=60, null=True),
        ),
    ]
