# Generated by Django 5.2.10 on 2026-02-05 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.CharField(choices=[('DAMAGED', 'Danificado/Quebrado'), ('EXPIRED', 'Prazo de Validade Expirado'), ('THEFT', 'Furto/Roubo Identificado'), ('INTERNAL', 'Consumo Interno Autorizado')], max_length=20)),
                ('photo_evidence', models.ImageField(help_text='Foto real do item danificado', upload_to='stock/wastes/%Y/%m/')),
                ('description', models.TextField(verbose_name='Relatório Detalhado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='compras.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.productvariant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
