# Generated by Django 5.2.10 on 2026-01-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('hash_value', models.CharField(help_text='Hash assinado (RSA Signature)', max_length=255)),
                ('hash_control', models.CharField(default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SAFTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_certificate_number', models.CharField(default='000/AGT/2026', max_length=50)),
                ('private_key', models.TextField(help_text='Chave privada RSA para assinatura das faturas')),
                ('public_key', models.TextField()),
                ('version', models.CharField(default='1.01_01', max_length=20)),
            ],
        ),
    ]
