# Generated by Django 5.2.10 on 2026-01-23 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('depreciation_years', models.PositiveIntegerField(help_text='Vida útil em anos')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('purchase_date', models.DateField()),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('residual_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Valor final estimado', max_digits=12)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='inventory/qrcodes/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.assetcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
