# Generated by Django 5.2.10 on 2026-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='unit',
            field=models.CharField(default='UN', help_text='Ex: UN, KG, LT, CX', max_length=20, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='residual_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
