# Generated by Django 5.2.10 on 2026-03-06 15:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('EXAM', 'Prova/Exame'), ('HOLIDAY', 'Feriado/Pausa'), ('EVENT', 'Evento/Actividade'), ('MEETING', 'Reunião de Pais')], max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('executive_report_emails', models.TextField(blank=True, help_text='E-mails que receberão o BI mensal (separe por vírgula).')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='AcademicGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_pedagogical_break', models.BooleanField(default=False, verbose_name='Pausa Pedagógica (Bloquear Notas)')),
            ],
            options={
                'verbose_name': 'Configuração Académica Global',
                'verbose_name_plural': 'Configurações Académicas Globais',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Ex: 2025/2026', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Ex: 10ª A', max_length=50)),
                ('capacity', models.PositiveIntegerField(default=30, help_text='Limite definido pelo Admin')),
                ('period', models.CharField(choices=[('AM', 'Manhã'), ('PM', 'Tarde'), ('NIGHT', 'Noite')], max_length=20)),
                ('room_number', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Class (Turma)',
                'verbose_name_plural': 'Classes (Turmas)',
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('level', models.CharField(choices=[('HIGH_SCHOOL', 'Ensino Médio (General)'), ('TECHNICAL', 'Técnico (Vocational)'), ('PROFESSIONAL', 'Profissional (Training)')], default='HIGH_SCHOOL', max_length=20)),
                ('duration_years', models.PositiveIntegerField(default=3)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(help_text='Ex: 10ª Classe', max_length=50)),
                ('level_index', models.PositiveIntegerField(help_text='Sequence number (1, 2, 3...)')),
            ],
            options={
                'ordering': ['course', 'level_index'],
            },
        ),
        migrations.CreateModel(
            name='LessonPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('topic', models.CharField(max_length=255, verbose_name='Sumário/Tema')),
                ('content', models.TextField(verbose_name='Conteúdo Programático')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_signed', models.BooleanField(default=False, help_text='Assinatura eletrónica do professor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('field_changed', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('unjustified_absences', models.PositiveIntegerField(default=0, verbose_name='Faltas Injustificadas')),
                ('is_failed_by_attendance', models.BooleanField(default=False, verbose_name='Retido por Faltas')),
                ('mac1', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='MAC 1')),
                ('npp1', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPP 1')),
                ('npt1', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPT 1')),
                ('mt1', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='MT 1')),
                ('mac2', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='MAC 2')),
                ('npp2', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPP 2')),
                ('npt2', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPT 2')),
                ('mt2', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='MT 2')),
                ('mac3', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='MAC 3')),
                ('npp3', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPP 3')),
                ('npt3', models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPT 3')),
                ('mt3', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='MT 3')),
                ('mf', models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='Média Final')),
                ('exame_nacional', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
            ],
            options={
                'verbose_name': 'Nota do Aluno',
                'verbose_name_plural': 'Notas dos Alunos',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('workload_hours', models.PositiveIntegerField(help_text='Carga horária anual')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('denied', 'Negado')], default='pending', max_length=20)),
                ('is_resolved', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
