# Generated by Django 5.2.10 on 2026-03-06 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='academicglobal',
            name='break_exceptions',
            field=models.ManyToManyField(blank=True, related_name='pedagogical_break_overrides', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='class',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.academicyear'),
        ),
        migrations.AddField(
            model_name='class',
            name='main_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='academicevent',
            name='klass',
            field=models.ForeignKey(blank=True, help_text='Vazio para toda a escola', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.class'),
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_courses', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='academic.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.gradelevel'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teachersubject'),
        ),
        migrations.AddField(
            model_name='studentauditlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
