# Generated by Django 5.2.10 on 2026-01-23 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='main_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='academicevent',
            name='klass',
            field=models.ForeignKey(blank=True, help_text='Vazio para toda a escola', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.class'),
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_courses', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_levels', to='academic.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academic.gradelevel'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='klass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic.class'),
        ),
    ]
