# Generated by Django 5.2.10 on 2026-03-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('BASE', 'Ensino de Base (1 ao II)'), ('HIGH_SCHOOL', 'Ensino Médio (Puniv)'), ('TECHNICAL', 'Médio Técnico (Vocational-Politécnico)'), ('PROFESSIONAL', 'Formação Profissional (Training)')], default='HIGH_SCHOOL', max_length=20),
        ),
    ]
