# Generated by Django 5.2.10 on 2026-02-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_lessonplan_studentauditlog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentgrade',
            options={'verbose_name': 'Nota do Aluno', 'verbose_name_plural': 'Notas dos Alunos'},
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='mac2',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='MAC 2'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='mac3',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='MAC 3'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='mf',
            field=models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='Média Final'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='mt2',
            field=models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='MT 2'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='mt3',
            field=models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='MT 3'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='npp2',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPP 2'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='npp3',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPP 3'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='npt2',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPT 2'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='npt3',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4, verbose_name='NPT 3'),
        ),
        migrations.AlterField(
            model_name='studentgrade',
            name='mt1',
            field=models.DecimalField(decimal_places=1, default=0.0, editable=False, max_digits=4, verbose_name='MT 1'),
        ),
    ]
