# Generated by Django 5.2.10 on 2026-03-17 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_course_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço da mensalidade padrão', max_digits=12),
        ),
        migrations.AddField(
            model_name='gradelevel',
            name='fee_percentage_increase',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Percentagem acima do preço padrão (Ex: 10.00 para +10%)', max_digits=5),
        ),
    ]
