# Generated by Django 5.2.10 on 2026-02-02 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_alter_studentgrade_options_studentgrade_mac2_and_more'),
        ('teachers', '0002_teacher_exit_date_teacher_exit_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicevent',
            name='break_exceptions',
            field=models.ManyToManyField(blank=True, related_name='pedagogical_break_overrides', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='academicevent',
            name='executive_report_emails',
            field=models.TextField(blank=True, help_text='E-mails que receberão o BI mensal (separe por vírgula).'),
        ),
        migrations.AddField(
            model_name='academicevent',
            name='is_pedagogical_break',
            field=models.BooleanField(default=False, help_text='Se ativo, professores não podem lançar ou editar notas.', verbose_name='Pausa Pedagógica (Bloquear Notas)'),
        ),
    ]
