# Generated by Django 5.2.10 on 2026-02-05 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_academicevent_break_exceptions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgrade',
            name='exame_nacional',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='is_failed_by_attendance',
            field=models.BooleanField(default=False, verbose_name='Retido por Faltas'),
        ),
        migrations.AddField(
            model_name='studentgrade',
            name='unjustified_absences',
            field=models.PositiveIntegerField(default=0, verbose_name='Faltas Injustificadas'),
        ),
    ]
