# Generated by Django 5.2.10 on 2026-03-17 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_course_monthly_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration_years',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Anos totais. Use 0.08 para ~1 mês, 0.25 para 3 meses, etc.', max_digits=5),
        ),
    ]
