# Generated by Django 5.2.10 on 2026-03-17 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_alter_course_duration_years'),
        ('fiscal', '0002_alter_documentofiscal_tipo_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Regime de IVA'),
        ),
    ]
