# Generated by Django 5.2.10 on 2026-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_studentgrade_exame_nacional_and_more'),
        ('teachers', '0002_teacher_exit_date_teacher_exit_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicevent',
            name='break_exceptions',
        ),
        migrations.RemoveField(
            model_name='academicevent',
            name='is_pedagogical_break',
        ),
        migrations.CreateModel(
            name='AcademicGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_pedagogical_break', models.BooleanField(default=False, verbose_name='Pausa Pedagógica (Bloquear Notas)')),
                ('break_exceptions', models.ManyToManyField(blank=True, related_name='pedagogical_break_overrides', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Configuração Académica Global',
                'verbose_name_plural': 'Configurações Académicas Globais',
            },
        ),
    ]
