# Generated by Django 5.2.10 on 2026-02-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_academicevent_break_exceptions_and_more'),
        ('customers', '0002_alter_client_institution_type_subagent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicglobal',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.client'),
        ),
    ]
