# Generated by Django 5.2.10 on 2026-03-17 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_course_tax_type'),
        ('fiscal', '0002_alter_documentofiscal_tipo_documento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='tax_type',
        ),
        migrations.AddField(
            model_name='course',
            name='taxa_iva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.taxaivaagt', verbose_name='Taxa de IVA Aplicável'),
        ),
    ]
