# Generated by Django 5.2.10 on 2026-03-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_remove_course_tax_type_course_taxa_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrollment_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço da matrícula/inscrição padrão', max_digits=12),
        ),
    ]
