# Generated by Django 5.2.10 on 2026-02-26 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0009_academicglobal_tenant_academicyear_tenant'),
        ('customers', '0002_alter_client_institution_type_subagent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicglobal',
            name='tenant',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_config', to='customers.client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='tenant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='customers.client'),
            preserve_default=False,
        ),
    ]
