# Generated by Django 5.2.10 on 2026-03-20 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_course_enrollment_fee'),
        ('finance', '0003_delete_serviceprovider_alter_feetype_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='enrollment_fee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='monthly_fee',
        ),
        migrations.AddField(
            model_name='course',
            name='default_enrollment_fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_enrollment', to='finance.feetype', verbose_name='Tipo de Matrícula Padrão'),
        ),
        migrations.AddField(
            model_name='course',
            name='default_monthly_fee_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses_monthly', to='finance.feetype', verbose_name='Tipo de Mensalidade Padrão'),
        ),
        migrations.AlterField(
            model_name='gradelevel',
            name='fee_percentage_increase',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Ex: 10.00 para cobrar 10% a mais que o valor base do curso no FeeType', max_digits=5),
        ),
    ]
