# Generated by Django 5.2.10 on 2026-03-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_remove_course_enrollment_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradelevel',
            name='total_monthly_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Preço final calculado (Base + % + IVA) para esta classe.', max_digits=12),
        ),
    ]
