# Generated by Django 5.2.10 on 2026-01-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='exit_date',
            field=models.DateField(blank=True, help_text='Data de desligamento', null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='exit_reason',
            field=models.CharField(blank=True, choices=[('RESIGNATION', 'Demissão Voluntária'), ('TERMINATION', 'Rescisão Contratual'), ('DISMISSAL', 'Justa Causa (Expulsão)'), ('REDUNDANCY', 'Redução de Pessoal'), ('RETIREMENT', 'Reforma'), ('OTHER', 'Outros')], max_length=20, null=True, verbose_name='Motivo de Saída'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='final_evaluation',
            field=models.TextField(blank=True, help_text='Avaliação final de desempenho ou notas do RH.', null=True, verbose_name='Avaliação / Obs.'),
        ),
    ]
