# Generated by Django 5.2.10 on 2026-03-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert_type', models.CharField(default='IMPOSSIBLE_TRAVEL', max_length=50)),
                ('last_ip', models.GenericIPAddressField()),
                ('current_ip', models.GenericIPAddressField()),
                ('last_location', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('HIGH', 'Crítico'), ('MED', 'Médio')], max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='CREATE, UPDATE, DELETE, LOGIN', max_length=50)),
                ('object_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Extra context like changed fields', null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='object_type')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
