# Generated by Django 5.2.10 on 2026-02-05 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('alert_type', models.CharField(default='IMPOSSIBLE_TRAVEL', max_length=50)),
                ('last_ip', models.GenericIPAddressField()),
                ('current_ip', models.GenericIPAddressField()),
                ('last_location', models.CharField(max_length=255)),
                ('current_location', models.CharField(max_length=255)),
                ('is_resolved', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('HIGH', 'Crítico'), ('MED', 'Médio')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
